import test from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {readdir,readFile} from 'node:fs/promises'
import path from 'node:path'
import {DatabaseSync} from 'node:sqlite'
import {fixture,actor,until,logger} from './helpers/economicFixture.js'
import AutonomousCore from '../src/core/autonomousCore.js'
import {classifyLots,summarizeObservation,modelFromHistory} from '../src/core/market/marketStatistics.js'
import {normalizeWorkerEvent} from '../src/events/workerEventNormalizer.js'

const policy=(f,values)=>f.core.store.updateOperationsPolicy(values,f.core.store.operationsPolicy().revision)
function observe(f,{itemId=1,at=Date.now(),spread=true}={}){
    const p=f.core.store.runtimeSettings(),lots=Array.from({length:20},(_,i)=>({amount:1,totalPrice:20,seller:'Seller'+i}))
    if(spread)lots.push({amount:2,totalPrice:20,seller:'Wholesale'})
    const s=summarizeObservation(classifyLots(lots,new Set(),p));f.core.marketStore.ownNames()
    const m={...modelFromHistory(s,Array(5).fill(s)),itemId,serverId:1,realm:101,lastObservedAt:at,ownershipFingerprint:f.core.marketStore.namesFingerprint,segmentation:{retailMax:p.marketRetailMaxAmount,mediumMax:p.marketMediumMaxAmount}}
    f.store.prepare('INSERT INTO marketModels VALUES(?,?,?,?,?) ON CONFLICT(serverId,realm,itemId) DO UPDATE SET observedAt=excluded.observedAt,document=excluded.document').run(1,101,itemId,at,JSON.stringify(m));f.store.db.exec('UPDATE marketMetadata SET revision=revision+1')
    return f.core.tradingSnapshot().plans.find(p=>p.itemId===itemId)
}
async function setup(t,{arm=true,enable=true,proxy=true,connected=true,...options}={}){
    const f=await fixture(t,{lots:[1],...options})
    policy(f,{automationEnabled:true,allocationEnabled:false,autonomousTradingEnabled:false,capacity:{maximum:options.count??1},roles:{reseller:{target:options.count??1,maximum:options.count??1}},liveValidation:{enabled:true,itemId:1,maxPurchaseCommitment:10}})
    f.plan=observe(f);f.core.proxies.probe=()=>true
    if(proxy){
        f.core.proxies.save({name:'Test SOCKS',host:'127.0.0.1',port:1080,username:'private-proxy-user',password:'private-proxy-password'})
        const b=f.core.readActual().bots[0];f.incarnation=b.incarnationId
        f.core.proxies.reserve({botId:b.botId,actionId:'test-action',incarnationId:b.incarnationId});f.core.proxies.spawned(b.incarnationId,process.pid)
        if(connected)f.core.proxies.transport(b.incarnationId,'PROXY_TRANSPORT_CONNECTED',randomUUID())
    }
    if(arm)f.core.liveValidation.arm({expectedGeneration:0},actor)
    if(enable)policy(f,{autonomousTradingEnabled:true})
    return f
}
const submit=f=>f.core.economic.submitAutonomous(f.plan.planId,f.core.tradingExecution)
const rows=f=>f.core.economic.store.rows()
const consumeState=f=>f.core.liveValidation.fuse().state
async function newer(f){await new Promise(r=>setTimeout(r,3));f.plan=observe(f);return f.plan}

test('validation defaults disabled, unarmed and has no implicit budget',async t=>{const f=await fixture(t);assert.deepEqual(f.core.liveValidation.policy(),{enabled:false,itemId:null,maxQuantity:1,maxPurchaseCommitment:null,maxAutonomousWorkloads:1});assert.equal(consumeState(f),'UNARMED')})
test('armed fuse survives database reopen unchanged',async t=>{const f=await setup(t,{enable:false}),before=f.core.liveValidation.fuse();f.store.close();await f.store.init();assert.deepEqual(f.core.liveValidation.fuse(),before)})
test('unarmed fuse blocks creation',async t=>{const f=await setup(t,{arm:false});assert.throws(()=>submit(f),/FUSE_UNARMED/);assert.equal(rows(f).length,0)})
test('viewing preflight is observational and does not consume or dispatch',async t=>{const f=await setup(t);for(let i=0;i<5;i++){const p=f.core.liveValidation.preflight();assert.equal(p.ready,true);assert.equal(p.preview.targetQuantity,1)}assert.equal(consumeState(f),'ARMED');assert.equal(rows(f).length,0);assert.equal(f.sent.length,0);assert.equal(f.transactions.length,0)})
test('safe preview available with autonomous OFF but execution blocked',async t=>{const f=await setup(t,{enable:false}),v=f.core.liveValidation.preflight();assert.equal(v.ready,false);assert.ok(v.blockers.includes('TRADING_EXECUTION_DISABLED'));assert.equal(v.preview.targetQuantity,1);assert.equal(v.preview.botId,1);assert.throws(()=>submit(f),/TRADING_EXECUTION_DISABLED/);assert.equal(consumeState(f),'ARMED')})
test('effective quantity clamps to one without changing the TradingPlan',async t=>{const f=await setup(t),before=f.core.tradingSnapshot().plans[0],row=submit(f);assert.equal(before.targetQuantity,2);assert.equal(row.targetQuantity,1);assert.equal(row.liveValidation.quantityReduced,true);assert.equal(f.core.tradingSnapshot().plans[0].targetQuantity,2);assert.equal(row.sourcePlanId,before.planId)})
test('backend preview exactly matches bound admission terms and proxy',async t=>{const f=await setup(t),v=f.core.liveValidation.preflight(),row=submit(f);for(const k of ['itemId','targetQuantity','maxBuyPricePerItem','targetSellPricePerItem','botId'])assert.equal(v.preview[k],row.request[k]);assert.equal(v.preview.maximumPurchaseCommitment,row.maxBuyPricePerItem*row.targetQuantity);assert.equal(v.preview.incarnationId,row.liveValidation.incarnationId);assert.deepEqual(v.preview.proxy,row.liveValidation.proxy)})
test('positive explicit validation cap is required to arm',async t=>{const f=await setup(t,{arm:false,enable:false});policy(f,{liveValidation:{maxPurchaseCommitment:null}});assert.throws(()=>f.core.liveValidation.arm({expectedGeneration:0},actor),/CAP_REQUIRED/);assert.throws(()=>policy(f,{liveValidation:{maxPurchaseCommitment:0}}));assert.equal(consumeState(f),'UNARMED')})
test('validation hard cap blocks purchase',async t=>{const f=await setup(t,{arm:false,enable:false});policy(f,{liveValidation:{maxPurchaseCommitment:9}});f.core.liveValidation.arm({expectedGeneration:0},actor);policy(f,{autonomousTradingEnabled:true});assert.throws(()=>submit(f),/VALIDATION_PURCHASE_CAP/);assert.equal(consumeState(f),'ARMED')})
test('normal stricter commitment wins after quantity clamp',async t=>{const f=await setup(t);policy(f,{autonomousTradingMaxPurchaseValue:9});assert.throws(()=>submit(f),/AUTONOMOUS_PURCHASE_VALUE_LIMIT/);policy(f,{autonomousTradingMaxPurchaseValue:10});assert.equal(submit(f).targetQuantity,1)})
test('wrong item cannot use an armed fuse',async t=>{const f=await setup(t);f.store.db.exec(`INSERT INTO itemsData VALUES(2,'Pear','pear','{"minecraftName":"pear"}')`);f.plan=observe(f,{itemId:2});assert.throws(()=>submit(f),/WRONG_ITEM/);assert.equal(consumeState(f),'ARMED')})
test('HOLD and expired evidence cannot consume fuse',async t=>{const f=await setup(t);f.plan=observe(f,{spread:false});assert.throws(()=>submit(f),/PLAN_HOLD/);f.plan=observe(f,{at:Date.now()-400000});assert.throws(()=>submit(f),/PLAN_HOLD|PLAN_EXPIRED/);assert.equal(consumeState(f),'ARMED')})
test('item disabled invalidates admission',async t=>{const f=await setup(t);f.core.store.setOverride(1,{disabled:true},f.core.store.revision());assert.throws(()=>submit(f),/SUPERSEDED/);assert.equal(consumeState(f),'ARMED')})
for(const kind of ['UNCERTAIN','residual'])test(`existing ${kind} blocks validation`,async t=>{const f=await setup(t,{count:2});const manual=await f.submit({botId:2});f.core.economic.store.save({...manual,status:kind==='UNCERTAIN'?'UNCERTAIN':'FAILED',botId:2,progress:{...manual.progress,boughtQuantity:1,listedQuantity:0}});assert.throws(()=>submit(f),/ITEM_ECONOMIC_UNCERTAIN|RESIDUAL_INVENTORY_REVIEW_REQUIRED/);assert.equal(consumeState(f),'ARMED')})
test('unavailable Reseller cannot consume fuse',async t=>{const f=await setup(t);f.core.store.setControl(1,{manualHold:true});const pre=f.core.liveValidation.preflight();assert.equal(pre.ready,false);assert.ok(pre.blockers.includes('NO_ELIGIBLE_RESELLER'));assert.throws(()=>submit(f),/NO_ELIGIBLE_RESELLER/)})
for(const kind of ['missing','disconnected','wrongIncarnation'])test(`proxy ${kind} blocks without direct fallback`,async t=>{const f=await setup(t,{proxy:kind!=='missing',connected:kind!=='disconnected'});if(kind==='wrongIncarnation')f.store.db.exec("UPDATE proxyReservations SET incarnationId='obsolete'");const v=f.core.liveValidation.preflight();assert.ok(v.blockers.some(b=>b.startsWith('VALIDATION_PROXY')));assert.throws(()=>submit(f),/VALIDATION_PROXY/);assert.equal(consumeState(f),'ARMED');assert.equal(f.transactions.length,0)})
test('accepted request atomically consumes fuse before any worker assignment',async t=>{const f=await setup(t);let witnessed=false;f.eventBus.onAny(e=>{if(e.type==='core.economic.changed'&&e.payload.status==='PENDING'){witnessed=true;assert.equal(consumeState(f),'CONSUMED');assert.equal(f.sent.length,0)}});const row=submit(f);assert.equal(witnessed,true);assert.equal(f.core.liveValidation.fuse().workloadId,row.workloadId);assert.equal(f.transactions.length,0)})
test('failed workload persistence rolls back consumption',async t=>{const f=await setup(t),original=f.core.economic.store.save;f.core.economic.store.save=()=>{throw new Error('INJECTED_WRITE_FAILURE')};try{assert.throws(()=>submit(f),/INJECTED_WRITE_FAILURE/)}finally{f.core.economic.store.save=original}assert.equal(consumeState(f),'ARMED');assert.equal(rows(f).length,0)})
test('repeat delivery and newer plans cannot create a second workload',async t=>{const f=await setup(t);const first=submit(f);assert.equal(submit(f).workloadId,first.workloadId);await newer(f);for(let i=0;i<3;i++)await f.core.evaluateNow();assert.equal(rows(f).length,1);assert.equal(consumeState(f),'CONSUMED')})
test('restart never re-arms or creates a replacement attempt',async t=>{const f=await setup(t);await f.core.evaluateNow();await f.core.stop();const next=new AutonomousCore({dataBaseManager:{store:f.store},botManager:f.manager,eventBus:f.eventBus,logger,configurationService:{async sync(){}}});next.schedule=()=>{};try{await next.start();await next.evaluateNow();assert.equal(next.liveValidation.fuse().state,'CONSUMED');assert.equal(next.economic.store.rows().length,1);assert.equal(next.economic.store.rows()[0].status,'UNCERTAIN')}finally{await next.stop()}})
for(const status of ['COMPLETED','FAILED','CANCELLED','UNCERTAIN'])test(`${status} never re-arms validation fuse`,async t=>{const f=await setup(t),row=submit(f);f.core.economic.store.save({...row,status});await newer(f);assert.throws(()=>submit(f),/FUSE_CONSUMED/);assert.equal(consumeState(f),'CONSUMED');assert.equal(rows(f).length,1)})
test('stale incarnation result cannot add timeline or satisfy current execution',async t=>{const f=await setup(t);await f.core.evaluateNow();const row=rows(f)[0],before=JSON.stringify(row.timeline);f.core.economic.handle({type:'bot.economic.result',source:{botId:1},payload:{workloadId:row.workloadId,incarnationId:'stale',lifecycleEpoch:row.lifecycleEpoch,workloadGeneration:row.workloadGeneration,sequence:100,status:'COMPLETED',progress:{boughtQuantity:1,listedQuantity:1,purchaseValue:10},evidence:{code:'LISTING_ACKNOWLEDGED'}}});assert.equal(JSON.stringify(rows(f)[0].timeline),before);assert.equal(rows(f)[0].status,'ADMITTED')})
test('live evidence timeline reconstructs one buy/list through existing mechanics',async t=>{
    const f=await setup(t,{transport:true});await f.core.evaluateNow();await until(()=>rows(f)[0]?.status==='COMPLETED');const row=rows(f)[0],codes=row.timeline.map(e=>e.code)
    for(const code of ['TRADING_PLAN_SELECTED','AUTONOMOUS_ADMISSION_ACCEPTED','VALIDATION_FUSE_CONSUMED','ECONOMIC_WORKLOAD_CREATED','BOT_SELECTED','WORKLOAD_DISPATCHED','INVENTORY_BEFORE','BUY_LOT_SELECTED','BUY_CONFIRMATION_RESULT','BUY_ATTEMPT_STARTED','BUY_INVENTORY_RESULT','PURCHASE_ATTRIBUTED','LISTING_ATTEMPT_STARTED','LISTING_SERVER_RESULT','LISTING_ACKNOWLEDGED','TERMINAL_WORKLOAD_RESULT'])assert.ok(codes.includes(code),code)
    assert.ok(codes.indexOf('VALIDATION_FUSE_CONSUMED')<codes.indexOf('BUY_ATTEMPT_STARTED'));assert.deepEqual(f.transactions,['buy','list']);assert.equal(row.progress.boughtQuantity,1);assert.equal(row.progress.listedQuantity,1);assert.equal(row.timeline.find(e=>e.code==='BUY_INVENTORY_RESULT').data.afterCount,1);assert.equal(consumeState(f),'CONSUMED')
})
test('ambiguous listing outcome stays uncertain and consumed',async t=>{const f=await setup(t,{transport:true,listing:'timeout'});await f.core.evaluateNow();await until(()=>rows(f)[0]?.status==='UNCERTAIN');assert.equal(consumeState(f),'CONSUMED');assert.equal(rows(f)[0].timeline.at(-1).data.status,'UNCERTAIN');policy(f,{autonomousTradingEnabled:false});assert.throws(()=>f.core.liveValidation.arm({expectedGeneration:1},actor),/RECONCILIATION_REQUIRED/)})
test('credentials and raw evidence fields absent from preflight/snapshot/timeline',async t=>{const f=await setup(t);const raw={workloadId:'test',evidence:{code:'BUY_LOT_SELECTED',data:{count:1,password:'private-proxy-password',username:'private-proxy-user',telegram:'private-telegram-secret'}}};const normalized=normalizeWorkerEvent('bot:economic.result','bot.economic.result',raw);assert.deepEqual(normalized.evidence.data,{count:1});assert.doesNotMatch(JSON.stringify(f.core.snapshot()),/private-proxy-password|private-proxy-user|private-telegram-secret/);const source=await readFile(new URL('../src/minecraftBot/taskRunner/modes/reseller/resellerBuyer.js',import.meta.url),'utf8');assert.match(source,/code:'BUY_CONFIRMATION_CLICK_FAILED'/)})
test('arm is operator-only and requires autonomous off and a current generation',async t=>{const f=await setup(t,{arm:false});assert.throws(()=>f.core.liveValidation.arm({expectedGeneration:0},actor),/DISABLE_AUTONOMOUS/);policy(f,{autonomousTradingEnabled:false});assert.throws(()=>f.core.liveValidation.arm({expectedGeneration:0},{type:'core',id:'trading'}),/MANUAL_OPERATOR_REQUIRED/);f.core.liveValidation.arm({expectedGeneration:0},actor);assert.throws(()=>f.core.liveValidation.arm({expectedGeneration:0},actor),/FUSE_CONFLICT/)})
test('explicit rearm never bypasses reconciliation or old plan identity',async t=>{const f=await setup(t),row=submit(f);f.core.economic.store.save({...row,status:'FAILED'});policy(f,{autonomousTradingEnabled:false});f.core.liveValidation.arm({expectedGeneration:1},actor);policy(f,{autonomousTradingEnabled:true});assert.equal(submit(f).workloadId,row.workloadId);assert.equal(consumeState(f),'ARMED');await newer(f);assert.notEqual(submit(f).workloadId,row.workloadId);assert.equal(consumeState(f),'CONSUMED')})
test('configuration change invalidates previously armed fuse',async t=>{const f=await setup(t);policy(f,{liveValidation:{maxPurchaseCommitment:11}});assert.throws(()=>submit(f),/CONFIGURATION_CHANGED/);assert.equal(rows(f).length,0)})
test('proxy/worker replacement after creation cancels instead of rebinding',async t=>{const f=await setup(t),row=submit(f);f.core.proxies.clearTransport(f.incarnation);assert.equal(f.core.economic.dispatch({workloadId:row.workloadId,target:{botId:1}}),false);assert.equal(rows(f)[0].status,'CANCELLED');assert.equal(consumeState(f),'CONSUMED')})
test('disable action shuts off both modes without resetting consumed fuse',async t=>{const f=await setup(t);submit(f);f.core.liveValidation.disable({expectedRevision:f.core.store.operationsPolicy().revision},actor);assert.equal(f.core.store.operationsPolicy().autonomousTradingEnabled,false);assert.equal(f.core.liveValidation.policy().enabled,false);assert.equal(consumeState(f),'CONSUMED')})
test('manual workloads remain unchanged with validation armed',async t=>{const f=await setup(t,{enable:false,transport:true,lots:[2]});const result=await f.run();assert.equal(result.status,'COMPLETED');assert.equal(result.targetQuantity,2);assert.equal(result.source,'MANUAL');assert.equal(consumeState(f),'ARMED')})
test('normal autonomous mode preserves plan quantity and does not require a fuse',async t=>{const f=await setup(t,{arm:false,proxy:false});policy(f,{liveValidation:{enabled:false}});policy(f,{autonomousTradingEnabled:true});const row=submit(f);assert.equal(row.targetQuantity,2);assert.equal(row.liveValidation,undefined);assert.equal(consumeState(f),'UNARMED')})
test('v15 migration installs disabled/unarmed validation with no live budget',async t=>{const f=await fixture(t);f.store.db.exec("DROP TABLE liveValidationFuse; DELETE FROM schemaMigrations WHERE version=16; PRAGMA user_version=15; UPDATE operationsPolicy SET document=json_remove(document,'$.liveValidation')");f.store.close();await f.store.init();assert.equal(f.store.prepare('PRAGMA user_version').get().user_version,16);assert.equal(consumeState(f),'UNARMED');assert.equal(f.core.liveValidation.policy().enabled,false);assert.equal(f.core.liveValidation.policy().maxPurchaseCommitment,null);const dirs=await readdir(path.join(f.dir,'backups')),db=new DatabaseSync(path.join(f.dir,'backups',dirs[0],'afina-before-v16.db'),{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get().user_version,15);db.close();assert.deepEqual(f.store.prepare('PRAGMA foreign_key_check').all(),[])})
test('confirmation slot timeout is uncertain, never a safe retry signal',async t=>{
    const f=await setup(t,{transport:true}),client=f.workers[0].client,click=client.clickWindow
    client.clickWindow=async(...args)=>{await click.apply(client,args);if(client.currentWindow?.type==='confirmation')client.currentWindow.slots=[]}
    await f.core.evaluateNow();await until(()=>rows(f)[0]?.status==='UNCERTAIN')
    assert.equal(consumeState(f),'CONSUMED');assert.ok(rows(f)[0].timeline.some(e=>e.code==='BUY_CONFIRMATION_RESULT'&&e.data.outcome==='SLOT_MISSING'));assert.deepEqual(f.transactions,[])
})
test('transport exception details never enter economic diagnostic logs',async t=>{
    const captured=[],oldWarn=logger.warn;logger.warn=(...args)=>captured.push(args)
    try{const f=await setup(t,{transport:true,onConfirm:()=>{throw new Error('private-proxy-password')}});await f.core.evaluateNow();await until(()=>rows(f)[0]?.status==='UNCERTAIN');assert.doesNotMatch(JSON.stringify([captured,rows(f),f.results]),/private-proxy-password/);assert.ok(JSON.stringify(captured).includes('BUY_CONFIRMATION_CLICK_FAILED'))}finally{logger.warn=oldWarn}
})
test('v16 failed migration rolls back without arming or consuming anything',async t=>{
    const f=await fixture(t);f.store.db.exec('DELETE FROM schemaMigrations WHERE version=16; PRAGMA user_version=15');f.store.close();await assert.rejects(f.store.init())
    const db=new DatabaseSync(path.join(f.dir,'afina.db'));assert.equal(db.prepare('PRAGMA user_version').get().user_version,15);assert.equal(db.prepare('SELECT count(*) n FROM schemaMigrations WHERE version=16').get().n,0);assert.equal(db.prepare('SELECT state FROM liveValidationFuse').get().state,'UNARMED');db.exec('DROP TABLE liveValidationFuse');db.close();await f.store.init();assert.equal(consumeState(f),'UNARMED')
})
