import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm,readdir,readFile} from 'node:fs/promises'
import {EventEmitter} from 'node:events'
import {DatabaseSync} from 'node:sqlite'
import path from 'node:path'
import os from 'node:os'
import DatabaseStore from '../src/data/databaseStore.js'
import ProxyStore,{validateProxy} from '../src/resources/proxyStore.js'
import TelegramAccountStore from '../src/telegram/telegramAccountStore.js'
import {proxyConnect} from '../src/minecraftBot/worker/proxyTransport.js'
import BotProcess from '../src/botManager/botProcess.js'
import {mergeOperationsPolicy,defaultOperationsPolicy} from '../src/core/operationsPolicy.js'

const logger={child(){return this},withContext(){return this},info(){},warn(){},error(){}}
const input=(values={})=>({name:'Proxy',host:'localhost',port:1080,protocol:'socks5',username:'proxy-user',password:'proxy-secret',active:true,...values})
const tick=()=>new Promise(r=>setImmediate(r))
async function fixture(t){const dir=await mkdtemp(path.join(os.tmpdir(),'afina-proxy-')),store=new DatabaseStore({databasePath:path.join(dir,'afina.db')});await store.init();let capacity=2,exists=true;const proxies=new ProxyStore({store,capacity:()=>capacity,probe:()=>exists});t.after(async()=>{store.close();await rm(dir,{recursive:true,force:true})});let next=0;return {dir,store,proxies,capacity:n=>capacity=n,exists:v=>exists=v,add:v=>proxies.save(input(v)),reserve:(botId=++next)=>proxies.reserve({botId,actionId:'action-'+botId,incarnationId:'inc-'+botId})}}
test('proxy create/edit/redaction and durable reopen shape',async t=>{const f=await fixture(t),p=f.add();assert.equal(p.host,'localhost');assert.equal(p.password,undefined);assert.equal(p.username,undefined);assert.equal(f.proxies.save({proxyId:p.proxyId,name:'Edited'}).name,'Edited');assert.doesNotMatch(JSON.stringify(f.proxies.snapshot()),/proxy-secret|proxy-user/);assert.equal(f.store.prepare('SELECT password FROM proxies').get().password,'proxy-secret')})
for(const patch of [{host:'user:secret@host'},{host:'x/y'},{host:'a..b'},{port:0},{port:65536},{port:1.2},{protocol:'http'},{password:'x\n'},{username:''},{active:1},{name:''}])test('proxy validation '+JSON.stringify(patch),()=>assert.throws(()=>validateProxy(input(patch))))
for(const value of [0,-1,1001,1.5,'4',null])test('capacity validation '+String(value),()=>assert.throws(()=>mergeOperationsPolicy(defaultOperationsPolicy,{maximumBotsPerProxy:value})))
test('least-used stable tie breaker and exact capacity boundary',async t=>{const f=await fixture(t),a=f.add(),b=f.add({name:'second'});assert.equal(f.reserve().proxyId,a.proxyId);assert.equal(f.reserve().proxyId,b.proxyId);assert.equal(f.reserve().proxyId,a.proxyId);assert.equal(f.reserve().proxyId,b.proxyId);assert.throws(()=>f.reserve(),/PROXY_CAPACITY_EXHAUSTED/);assert.equal(f.proxies.snapshot().available,0)})
test('simultaneous actions cannot both reserve final slot',async t=>{const f=await fixture(t);f.capacity(1);f.add();const results=await Promise.allSettled([Promise.resolve().then(()=>f.reserve()),Promise.resolve().then(()=>f.reserve())]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.proxies.owned().length,1)})
test('inactive proxy excluded; deactivation and reduced limit preserve owners',async t=>{const f=await fixture(t),p=f.add();f.reserve();f.reserve();f.capacity(1);assert.equal(f.proxies.snapshot().proxies[0].overCapacity,true);f.proxies.save({proxyId:p.proxyId,active:false});assert.equal(f.proxies.owned().length,2);assert.throws(()=>f.reserve(),/NO_ELIGIBLE_PROXY/);f.proxies.save({proxyId:p.proxyId,active:true});assert.throws(()=>f.reserve(),/CAPACITY/)})
test('delete and endpoint edit blocked during ownership; unused delete succeeds',async t=>{const f=await fixture(t),p=f.add(),r=f.reserve();assert.throws(()=>f.proxies.remove(p.proxyId),/IN_USE/);assert.throws(()=>f.proxies.save({proxyId:p.proxyId,host:'other'}),/IN_USE/);f.proxies.release(r.incarnationId,'PROCESS_EXITED');f.proxies.remove(p.proxyId);assert.equal(f.proxies.rows().length,0)})
test('restart after inactive old proxy selects another; replacement cannot overlap old ownership',async t=>{const f=await fixture(t),p=f.add(),r=f.reserve(1),next=f.add({name:'second'});f.proxies.save({proxyId:p.proxyId,active:false});assert.throws(()=>f.proxies.reserve({botId:1,actionId:'replace',incarnationId:'new'}),/OWNERSHIP/);f.proxies.release(r.incarnationId,'PROCESS_EXITED');assert.equal(f.proxies.reserve({botId:1,actionId:'replace',incarnationId:'new'}).proxyId,next.proxyId)})
test('no proxies means no reservation',async t=>{const f=await fixture(t);assert.throws(()=>f.reserve(),/NO_ELIGIBLE_PROXY/)})
test('fresh database records the v13 migration receipt',async t=>{const f=await fixture(t);assert.equal(f.store.prepare('SELECT count(*) n FROM schemaMigrations WHERE version=13').get().n,1)})
test('migration failure rolls back v13 receipt and recovers after repair',async t=>{
 const f=await fixture(t);f.store.db.exec('DROP TABLE IF EXISTS liveValidationFuse; DELETE FROM schemaMigrations WHERE version=16; DROP INDEX IF EXISTS economic_source_plan; DROP INDEX IF EXISTS economic_autonomous_item; DELETE FROM schemaMigrations WHERE version=15; DROP TABLE tradingPlans; DELETE FROM schemaMigrations WHERE version=14; DROP TABLE proxyDiagnostics; DROP TABLE proxyReservations; DROP TABLE proxies; ALTER TABLE telegramAccounts DROP COLUMN active; DELETE FROM schemaMigrations WHERE version=13; PRAGMA user_version=12; CREATE TABLE proxies(bad INTEGER)');f.store.close();await assert.rejects(f.store.init())
 const db=new DatabaseSync(path.join(f.dir,'afina.db'));assert.equal(db.prepare('PRAGMA user_version').get().user_version,12);assert.equal(db.prepare('SELECT count(*) n FROM schemaMigrations WHERE version=13').get().n,0);db.exec('DROP TABLE proxies');db.close();await f.store.init();assert.equal(f.store.prepare('PRAGMA integrity_check').get().integrity_check,'ok')
})
for(const observed of [true,null])test('startup/IPC uncertainty preserves reservation '+observed,async t=>{const f=await fixture(t);f.add();const r=f.reserve();f.proxies.spawned(r.incarnationId,555);f.exists(observed);f.proxies.reconcile();assert.equal(f.proxies.owned().length,1)})
test('startup releases proven absent PID, retains unknown pre-spawn window',async t=>{const f=await fixture(t);f.add();const a=f.reserve(),b=f.reserve();f.proxies.spawned(a.incarnationId,555);f.exists(false);f.proxies.reconcile();assert.deepEqual(f.proxies.owned().map(r=>r.incarnationId),[b.incarnationId])})
test('stale incarnation cannot release a replacement',async t=>{const f=await fixture(t);f.add();const old=f.reserve(1);f.proxies.release(old.incarnationId,'PROCESS_EXITED');const r=f.proxies.reserve({botId:1,actionId:'next',incarnationId:'next'});f.proxies.release(old.incarnationId,'PROCESS_EXITED');assert.equal(f.proxies.owned()[0].incarnationId,r.incarnationId)})
test('guarded process reserves before fork, privately sends credentials, releases on exit only',async t=>{
 const f=await fixture(t);f.add();const child=new EventEmitter();Object.assign(child,{pid:555,connected:true});let init;child.send=m=>{init=m}
 const bot=new BotProcess({botId:1,accountData:{accountId:1},taskData:{type:'analyst'},serverData:{},logger,eventBus:{publish(){}},forkWorker:()=>{assert.equal(f.proxies.owned().length,1);return child}})
 bot.start({beforeSpawn:incarnationId=>f.proxies.reserve({botId:1,actionId:'start',incarnationId}),proxyLifecycle:f.proxies});child.emit('spawn');assert.equal(init.payload.proxy.password,'proxy-secret');child.emit('disconnect');assert.equal(f.proxies.owned().length,1);child.emit('exit',0,null);assert.equal(f.proxies.owned().length,0)
})
test('definitive fork failure releases the reserved slot',async t=>{const f=await fixture(t);f.add();const bot=new BotProcess({botId:1,accountData:{accountId:1},logger,eventBus:{publish(){}},forkWorker:()=>{throw new Error('fork failed')}});assert.throws(()=>bot.start({beforeSpawn:incarnationId=>f.proxies.reserve({botId:1,actionId:'a',incarnationId}),proxyLifecycle:f.proxies}));assert.equal(f.proxies.owned().length,0)})
for(const role of ['analyst','reseller'])test(role+' shared SOCKS5 connect receives credentials and target',async()=>{
 const socket=new EventEmitter();socket.destroy=()=>{};const client=new EventEmitter();client.setSocket=s=>assert.equal(s,socket);let options,connected=0;client.on('connect',()=>connected++)
 proxyConnect({proxy:{...input(),proxyId:1,reservationId:'r',incarnationId:'i'},incarnationId:'i',host:'minecraft.example',connect:async o=>{options=o;return {socket}}})(client);await tick();assert.equal(options.proxy.password,'proxy-secret');assert.equal(options.proxy.type,5);assert.equal(options.destination.host,'minecraft.example');assert.equal(connected,1)
})
for(const reason of ['Authentication failed proxy-secret','connection refused proxy-secret'])test('SOCKS failure is classified without credentials '+reason.split(' ')[0],async()=>{
 const client=new EventEmitter(),errors=[],diagnostics=[];client.on('error',e=>errors.push(e.message));client.setSocket=()=>assert.fail('fallback');proxyConnect({proxy:{...input(),proxyId:1,reservationId:'r',incarnationId:'i'},incarnationId:'i',host:'server',connect:async()=>{throw new Error(reason)},onDiagnostic:c=>diagnostics.push(c)})(client);await tick();assert.equal(errors.length,1);assert.doesNotMatch(JSON.stringify(errors),/proxy-secret/);assert.equal(diagnostics[0],reason.startsWith('Auth')?'PROXY_AUTHENTICATION_FAILED':'PROXY_CONNECTION_FAILED')
})
test('no authorized proxy and stale incarnation never reach any connector',()=>{for(const proxy of [null,{...input(),proxyId:1,reservationId:'r',incarnationId:'old'}])assert.throws(()=>proxyConnect({proxy,incarnationId:'new',host:'server',connect:()=>assert.fail('direct fallback')}),/AUTHORIZED_PROXY/)})
test('transport failure recorded separately and does not deactivate proxy',async t=>{const f=await fixture(t),p=f.add(),r=f.reserve();f.proxies.diagnostic(r.incarnationId,'PROXY_TRANSPORT_FAILED');assert.equal(f.proxies.snapshot().proxies[0].diagnostic.code,'PROXY_TRANSPORT_FAILED');assert.equal(f.proxies.snapshot().proxies[0].active,true);f.proxies.diagnostic(r.incarnationId,'secret');assert.equal(f.proxies.snapshot().proxies[0].diagnostic.code,'PROXY_TRANSPORT_FAILED')})
test('Telegram inactive excludes new assignment and preserves existing relationships',async t=>{const f=await fixture(t),tg=new TelegramAccountStore(f.store);const first=tg.save('+4711111111','session'),second=tg.save('+4722222222','session');tg.status(first,'connected');tg.status(second,'connected');f.store.db.exec("INSERT INTO accountsData(accountId,username,password) VALUES(1,'One','pw'),(2,'Two','pw'),(3,'Three','pw')");assert.equal(tg.assign(1,new Set([first,second])).telegramAccountId,first);tg.setActive(first,false);assert.equal(tg.account(1).telegramAccountId,first);assert.equal(tg.assign(2,new Set([first,second])).telegramAccountId,second);assert.throws(()=>tg.assign(1,new Set([first,second])),/INACTIVE/);tg.setActive(second,false);assert.throws(()=>tg.assign(3,new Set([first,second])),/capacity/i);tg.setActive(first,true);assert.equal(tg.assign(3,new Set([first,second])).telegramAccountId,first)})
test('v12 to v13 backup, active default, retained data and idempotent reopen',async t=>{const f=await fixture(t);f.store.db.exec("INSERT INTO telegramAccounts(phone,session,status) VALUES('+4711111111','secret','connected'); DROP TABLE IF EXISTS liveValidationFuse; DELETE FROM schemaMigrations WHERE version=16; DROP INDEX IF EXISTS economic_source_plan; DROP INDEX IF EXISTS economic_autonomous_item; DELETE FROM schemaMigrations WHERE version=15; DROP TABLE tradingPlans; DELETE FROM schemaMigrations WHERE version=14; DROP TABLE proxyDiagnostics; DROP TABLE proxyReservations; DROP TABLE proxies; ALTER TABLE telegramAccounts DROP COLUMN active; DELETE FROM schemaMigrations WHERE version=13; PRAGMA user_version=12");f.store.close();await f.store.init();assert.equal(f.store.prepare('PRAGMA user_version').get().user_version,16);assert.equal(f.store.prepare('SELECT active FROM telegramAccounts').get().active,1);assert.deepEqual(f.store.prepare('PRAGMA foreign_key_check').all(),[]);assert.equal(f.store.prepare('PRAGMA integrity_check').get().integrity_check,'ok');const dirs=await readdir(path.join(f.dir,'backups'));const db=new DatabaseSync(path.join(f.dir,'backups',dirs[0],'afina-before-v16.db'),{readOnly:true});assert.equal(db.prepare('PRAGMA user_version').get().user_version,12);assert.equal(db.prepare('SELECT session FROM telegramAccounts').get().session,'secret');db.close();f.store.close();await f.store.init();assert.equal((await readdir(path.join(f.dir,'backups'))).length,1)})
test('production Minecraft creation has mandatory shared transport',async()=>{const bot=await readFile('src/minecraftBot/bot.js','utf8');assert.match(bot,/const connect=proxyConnect/);assert.match(bot,/mineflayer.createBot\(\{\s*connect,/);assert.match(await readFile('src/botManager/botProcess.js','utf8'),/this.forkWorker===fork&&!proxy/);assert.doesNotMatch(await readFile('src/minecraftBot/worker/proxyTransport.js','utf8'),/net\.connect|createConnection\(\{host/ )})
